import { Group } from '@/types';

export const mockGroups: Group[] = [
  {
    id: '1',
    name: 'Downtown Young Professionals',
    description: 'A community for young professionals in downtown Toronto to grow in faith and fellowship.',
    location: 'Liberty Village Community Centre',
    meetingDay: 'Thursday',
    meetingTime: 'Evening',
    groupType: 'Mixed',
    capacity: 15,
    currentMemberCount: 12,
    isOpen: true,
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
    planningCenterUrl: 'https://planning.center/groups/1',
    latitude: 43.6426,
    longitude: -79.3927,
    campusLocation: 'Downtown'
  },
  {
    id: '2',
    name: 'Midtown Families',
    description: 'Perfect for families with children. We explore faith together while kids enjoy activities.',
    location: 'North Toronto Community Centre',
    meetingDay: 'Sunday',
    meetingTime: 'Afternoon',
    groupType: 'Mixed',
    capacity: 20,
    currentMemberCount: 16,
    isOpen: true,
    imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=400',
    planningCenterUrl: 'https://planning.center/groups/2',
    latitude: 43.6890,
    longitude: -79.3957,
    campusLocation: 'Midtown'
  },
  {
    id: '3',
    name: 'Hamilton Men\'s Study',
    description: 'Men gathering weekly to study scripture and support each other in faith and life.',
    location: 'Hamilton Community Church',
    meetingDay: 'Wednesday',
    meetingTime: 'Evening',
    groupType: 'Men',
    capacity: 12,
    currentMemberCount: 8,
    isOpen: true,
    imageUrl: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=400',
    planningCenterUrl: 'https://planning.center/groups/3',
    latitude: 43.2557,
    longitude: -79.8711,
    campusLocation: 'Hamilton'
  },
  {
    id: '4',
    name: 'Women of Faith - Downtown',
    description: 'A supportive community for women to grow spiritually and build lasting friendships.',
    location: 'King Street West Location',
    meetingDay: 'Tuesday',
    meetingTime: 'Evening',
    groupType: 'Women',
    capacity: 14,
    currentMemberCount: 14,
    isOpen: false,
    imageUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=400',
    planningCenterUrl: 'https://planning.center/groups/4',
    latitude: 43.6465,
    longitude: -79.3889,
    campusLocation: 'Downtown'
  },
  {
    id: '5',
    name: 'Young Adults - Midtown',
    description: 'Ages 18-25. Navigate life\'s transitions with peers who share your faith journey.',
    location: 'Yonge & Eglinton Area',
    meetingDay: 'Friday',
    meetingTime: 'Evening',
    groupType: 'Mixed',
    capacity: 18,
    currentMemberCount: 10,
    isOpen: true,
    imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=400',
    planningCenterUrl: 'https://planning.center/groups/5',
    latitude: 43.7057,
    longitude: -79.3957,
    campusLocation: 'Midtown'
  },
  {
    id: '6',
    name: 'Hamilton Couples',
    description: 'Married couples strengthening relationships through faith and community support.',
    location: 'Hamilton West End',
    meetingDay: 'Saturday',
    meetingTime: 'Morning',
    groupType: 'Mixed',
    capacity: 16,
    currentMemberCount: 12,
    isOpen: true,
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
    planningCenterUrl: 'https://planning.center/groups/6',
    latitude: 43.2642,
    longitude: -79.9171,
    campusLocation: 'Hamilton'
  },
  {
    id: '7',
    name: 'Downtown Bible Study',
    description: 'Deep dive into scripture with passionate believers in the heart of the city.',
    location: 'Financial District',
    meetingDay: 'Monday',
    meetingTime: 'Evening',
    groupType: 'Mixed',
    capacity: 12,
    currentMemberCount: 9,
    isOpen: true,
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    planningCenterUrl: 'https://planning.center/groups/7',
    latitude: 43.6481,
    longitude: -79.3816,
    campusLocation: 'Downtown'
  },
  {
    id: '8',
    name: 'Midtown Women\'s Circle',
    description: 'Women connecting over coffee, prayer, and meaningful conversations about faith.',
    location: 'Davisville Village',
    meetingDay: 'Thursday',
    meetingTime: 'Morning',
    groupType: 'Women',
    capacity: 10,
    currentMemberCount: 7,
    isOpen: true,
    imageUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=400',
    planningCenterUrl: 'https://planning.center/groups/8',
    latitude: 43.6998,
    longitude: -79.3957,
    campusLocation: 'Midtown'
  }
];

export const filterOptions = {
  locations: ['All Locations', 'Downtown', 'Midtown', 'Hamilton'],
  days: ['Any Day', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  times: ['Any Time', 'Morning', 'Afternoon', 'Evening'],
  types: ['⚥ Mixed', '♂ Men', '♀ Women']
};